# Generated by Django 3.2.4 on 2021-10-09 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 9, 8, 30, 14, 446099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_completed_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 8, 30, 14, 446099, tzinfo=utc)),
        ),
    ]
