# Generated by Django 3.2.4 on 2021-10-09 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_auto_20211009_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 14, 1, 8, 375917)),
        ),
    ]
