# Generated by Django 3.2.4 on 2021-10-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_alter_todo_date_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed_by',
            field=models.DateField(default=datetime.date(2021, 10, 9)),
        ),
    ]
