# Generated by Django 3.2.4 on 2021-11-04 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0006_auto_20211104_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_completed_by',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
