# Generated by Django 4.0.4 on 2023-06-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0009_alter_todo_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
